class AppRoute {
  static const HOME_USER = '/';
  static const MODALITIES_USER = '/modalities-user';
  static const AOVIVO_USER = '/aovivo-user';
  static const SETTINGS_USER = '/settings-user';
  static const ABOUTUS_USER = '/aboutus-user';
  static const MODALITY_USER = '/modality-user';
  static const CRONOGRAMA_USER = '/cronograma-user';
  static const EQUIPE_USER = '/equipe-user';
  static const RESULTADO_USER = '/resultado-user';
  static const LANDING = '/landing';
  static const PERFIL_USER = '/perfil-user';
  static const MAIN_TEAM = '/main-team';
  static const MODALITY_TEAM = '/modality-team';
  static const PLAYER_TEAM = '/player-team';
  static const ADDPLAYER_TEAM = '/addplayer-team';
  static const CREATETEAM_TEAM = '/createteam-team';
  static const MAIN_ORGANIZATION = '/main-organization';
  static const MAIN_ADMIN = '/main-admin';
  static const MAINPRIVILEGES_ADMIN = '/mainprivileges-admin';
  static const PRIVILEGESTEAM_ADMIN = '/privilegesteam-admin';
  static const PRIVILEGESTEAMPAGE_ADMIN = '/privilegesteampage-admin';
  static const PRIVILEGEORGANIZATION_ADMIN = '/privilegeorganization-admin';
  static const PRIVILEGEORGANIZATIONPAGE_ADMIN =
      '/privilegeorganizationpage-admin';
  static const PRIVILEGEORGANIZATIONADDMODALITY_ADMIN =
      '/privilegeorganizationaddmodality-admin';
  static const MODALITY_ADMIN = '/modality-admin';
  static const MODALITIES_ADMIN = '/modalities-admin';
  static const TEAM_ADMIN = '/team-admin';
  static const TEAMVIEW_ADMIN = '/teamview-admin';
  static const MODALITIESGAMES_ADMIN = '/modalitiesgames-admin';
  static const REGULATION_ADMIN = 'regulation-admin';
  static const MAINMANAGEMENT_ADMIN = '/mainmanagement-admin';
  static const RESTARTCHAMPIOSHIP_ADMIN = '/restartchampionship-admin';
  static const MANAGEMENTACCOUNT_ADMIN = '/managementaccount-admin';
  static const MANAGEMENTACCOUNTADD_ADMIN = '/managementaccountadd-admin';
  static const ADDTEAMS_ADMIN = '/addteams-admin';
  static const CHAMPIOSHIPPAGE_ADMIN = '/champioshippage-admin';
  static const INSERTMODALITIES_ADMIN = '/insertmodalities-admin';
  static const STARTGAME_ORGANIZATION = '/StartGame-organization';
  static const DETAILSGAME_ORGANIZATION = '/detailsgame-organization';
  static const INSERTRULE_ORGANIZATION = '/insertrule-organization';
  static const MAINMODALITIES_ORGANIZATION = '/mainmodalities-organization';
  static const STARTCHAMPIONSHIP_ADMIN = '/startchampionship-admin';
  static const ADDMODALITY_ADMIN = '/addmodality-admin';
  static const ADDGAME_ORGANIZATION = '/addgame-organization';
  static const MODALITYPAGE_ORGANIZATION = '/modalitypage-organization';
}
